//
//Messages related to graph frames as used to represent results form the labeled property graph model.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: org/polypheny/prism/graph_frame.proto

package prism

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The GraphFrame represents the non-relational result of a query in the labeled property graph model.
// If the query returns a relational result, such as when aggregations are used or specific properties are returned,
// a relational frame is used. The GraphFrame is used for results where a set of nodes, edges, or paths is returned.
// This selection is exclusive, meaning only one of the lists can be populated at a time. If a result produces multiple
// frames (used to transmit large results), all results will be of the same type (relational vs. graph) and contain the
// same element type (nodes, edges or paths).
type GraphFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Field used to represent a set of nodes as part of a result. If this field is populated all others must not be set.
	Nodes []*ProtoNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Field used to represent a set of edges as part of a result. If this field is populated all others must not be set.
	Edges []*ProtoEdge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	// Field used to represent a set of paths as part of a result. If this field is populated all others must not be set.
	Paths []*ProtoPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *GraphFrame) Reset() {
	*x = GraphFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_graph_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphFrame) ProtoMessage() {}

func (x *GraphFrame) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_graph_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphFrame.ProtoReflect.Descriptor instead.
func (*GraphFrame) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_graph_frame_proto_rawDescGZIP(), []int{0}
}

func (x *GraphFrame) GetNodes() []*ProtoNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphFrame) GetEdges() []*ProtoEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GraphFrame) GetPaths() []*ProtoPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_org_polypheny_prism_graph_frame_proto protoreflect.FileDescriptor

var file_org_polypheny_prism_graph_frame_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x1a, 0x1f, 0x6f, 0x72,
	0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01,
	0x0a, 0x0a, 0x47, 0x72, 0x61, 0x70, 0x68, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x64, 0x67,
	0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f,
	0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x42, 0x56,
	0x0a, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x42, 0x10, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x19, 0x6f, 0x72, 0x67, 0x2f, 0x70,
	0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x3b, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0xaa, 0x02, 0x0f, 0x50, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79,
	0x2e, 0x50, 0x72, 0x69, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_polypheny_prism_graph_frame_proto_rawDescOnce sync.Once
	file_org_polypheny_prism_graph_frame_proto_rawDescData = file_org_polypheny_prism_graph_frame_proto_rawDesc
)

func file_org_polypheny_prism_graph_frame_proto_rawDescGZIP() []byte {
	file_org_polypheny_prism_graph_frame_proto_rawDescOnce.Do(func() {
		file_org_polypheny_prism_graph_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_polypheny_prism_graph_frame_proto_rawDescData)
	})
	return file_org_polypheny_prism_graph_frame_proto_rawDescData
}

var file_org_polypheny_prism_graph_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_polypheny_prism_graph_frame_proto_goTypes = []any{
	(*GraphFrame)(nil), // 0: org.polypheny.prism.GraphFrame
	(*ProtoNode)(nil),  // 1: org.polypheny.prism.ProtoNode
	(*ProtoEdge)(nil),  // 2: org.polypheny.prism.ProtoEdge
	(*ProtoPath)(nil),  // 3: org.polypheny.prism.ProtoPath
}
var file_org_polypheny_prism_graph_frame_proto_depIdxs = []int32{
	1, // 0: org.polypheny.prism.GraphFrame.nodes:type_name -> org.polypheny.prism.ProtoNode
	2, // 1: org.polypheny.prism.GraphFrame.edges:type_name -> org.polypheny.prism.ProtoEdge
	3, // 2: org.polypheny.prism.GraphFrame.paths:type_name -> org.polypheny.prism.ProtoPath
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_polypheny_prism_graph_frame_proto_init() }
func file_org_polypheny_prism_graph_frame_proto_init() {
	if File_org_polypheny_prism_graph_frame_proto != nil {
		return
	}
	file_org_polypheny_prism_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_polypheny_prism_graph_frame_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GraphFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_polypheny_prism_graph_frame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_polypheny_prism_graph_frame_proto_goTypes,
		DependencyIndexes: file_org_polypheny_prism_graph_frame_proto_depIdxs,
		MessageInfos:      file_org_polypheny_prism_graph_frame_proto_msgTypes,
	}.Build()
	File_org_polypheny_prism_graph_frame_proto = out.File
	file_org_polypheny_prism_graph_frame_proto_rawDesc = nil
	file_org_polypheny_prism_graph_frame_proto_goTypes = nil
	file_org_polypheny_prism_graph_frame_proto_depIdxs = nil
}
